### ISSUE TITLE
Argument 1 passed to Illuminate\Auth\Middleware\Authenticate::authenticate() must be of the type array, object given.

### ISSUE THREAD

**Issue by Psiroulis** [sfelix-martins/passport-multiauth-demo#2]
Hello, 
Thanks and congratulations for the great work.
I am new to Laravel and php general and after following the instructions  I try to get a user through a middleware inside a prefix route in api.php

`Route::prefix('users')->group(function () { Route::middleware('auth:api')->get('/user', function (Request $request) {
         return $request->user();
     });
});`

And I have this error : 

Argument 1 passed to Illuminate\Auth\Middleware\Authenticate::authenticate() must be of the type array, object given, called in ...\vendor\smartins\passport-multiauth\src\Http\Middleware\MultiAuthenticate.php on line 83

I change line 83 in MultiAuthenticate.php from:

`$this->authenticate($request,$guard);`

to:

`$this->authenticate($guard);`

and it works. I don't know if it an issue or I make a mistake but I thought I have to mention it.

Thanks for your Time!!!

**Comment by sfelix-martins** [comment]
@Psiroulis Thanks for your issue! Did you cloned this sample project or installed `sfelix-martins\passport-multiauth` package another project?

It seems a version problem. Until version 5.6 of laravel framework the method `authenticate` accepted only one param with an array of `$guards`, as you can see [here](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Auth/Middleware/Authenticate.php). But on version 5.7 this method was [changed](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Auth/Middleware/Authenticate.php#L55) to accept the `$request` on first param. Check it, please!

**Comment by Psiroulis** [comment]
@sfelix-martins Hi, I istalled the package to another project and my laravel version is 5.6.39 so from what you say this is the reason that the `$request` argument is not accepted.
Thanks for your time!

**Comment by sfelix-martins** [comment]
I understood. Probably you installed the version 4.0 of the package. The version compatible with laravel 5.6 is the version 3.0 of the package.

Merry christmas!

**Comment by Psiroulis** [comment]
Ok I will fix it. Thank you very much for your help!
Merry christmas!
