### ISSUE TITLE
api/login error getting unautuenticated issue, pls help me

### ISSUE THREAD

**Issue by mdmusaib** [sfelix-martins/passport-multiauth-demo#3]

**Comment by sfelix-martins** [comment]
@mdmusaib Please, give me more details how to simulate the error. Are you using this demo project or an installation of `passport-multiauh` in another laravel project? What steps did you follow until you found the error? Thanks

**Comment by mdmusaib** [comment]
@sfelix-martins  I'm using the demo project,I've just cloned it and done with the required execution of commands and when i hot api/login in post with the parameters like username,password,provider, it displaying {Unauthenticated } so I need to do the multiple auth using passport api in laravel for one of my project, so i got you github link from  google as i hope it would be the great way to help me to get it work done, so pls help me to do the work

**Comment by sfelix-martins** [comment]
@mdmusaib I think that the problem is [here](https://github.com/sfelix-martins/passport-multiauth-demo/blob/master/app/Http/Controllers/LoginController.php#L30). Check what's happening on `attempt()` method. Check your users credentials too. If nothing resolves, send me your project by email and I'll take a look.

**Comment by mdmusaib** [comment]
@sfelix-martins  Exactly as you said the problem is the that only, I've checked  the  request parameters also , but the thing is not understanding what's happening under the hood, I would like to discuss one more thing with you the tables all are empty initially as like when i do php artisan migrate, the same i didn't add anything,

**Comment by sfelix-martins** [comment]
@mdmusaib I don't understood very well. Did you created an user or admin on database?

**Comment by mdmusaib** [comment]
Yeah I've created a user by manually  from phpmyadmin, even though it not workings, please share me the steps i should do after running php artisan migrate, it will be great help.

**Comment by mdmusaib** [comment]
If you really want the code I'm ready to share to by email,

**Comment by mdmusaib** [comment]
If you really want the code I'm ready to share to by email,

**Comment by sfelix-martins** [comment]
What's password encryption did you used to create the user? The default laravel hashing are be used to check credentials. I thinks that you need create your user or admin creating the password hash with `bcrypt()` laravel helper. E.g.:

```php
User::create([
    'name' => 'Samuel'
    'email' => 'sfelix_martins@hotmail.com',
    'password' => bcrypt('secret'),
])
```

Check it please.

**Comment by mdmusaib** [comment]
Looking  forward to hear from you, kindly reach out ASAP

**Comment by mdmusaib** [comment]
@sfelix-martins  Thank you very much, I got the output, it's working fine now, but i have one doubt, I have created a user with id=1, and in oauth_access_token the user_id=1 that's fine, but I also created a admin
with the id=1,and in oauth_access_token again the  user_id=1 but the only thing is the token differ I want to know this could cause any problem in futur?

**Comment by mdmusaib** [comment]
Thanks a lot, for your kindly help

**Comment by mdmusaib** [comment]
![screenshot 30](https://user-images.githubusercontent.com/19144712/50532764-19cc1e80-0b44-11e9-8dfa-a51cd036ba83.png)

how to i install in my project

**Comment by sfelix-martins** [comment]
@mdmusaib responding your question about registries on tables: exists another table called `oauth_access_token_providers`. This table contains the relationship between the correct user table (admins, users, etc) and the access tokens on `oauth_access_tokens` table. I think that it is not the best tables structure, but to stay compatible with Laravel Passport original package it was necessary. I am opened to suggestions, and pull requests :D. Thanks!
