### ISSUE TITLE
how do i install passport-multiauth-demo to existing project

### ISSUE THREAD

**Issue by mdmusaib** [sfelix-martins/passport-multiauth-demo#4]

**Comment by mdmusaib** [comment]
![50532764-19cc1e80-0b44-11e9-8dfa-a51cd036ba83](https://user-images.githubusercontent.com/19144712/50535960-62e89680-0b75-11e9-9752-19bf1ea256ee.png)


@sfelix-martins  How Do i install this package, If I want to implement in another project, I tryed to install from composer this is the error I'm getting, pls help  me to solve this issue

**Comment by sfelix-martins** [comment]
@mdmusaib this project is a sample how to implements the [passport multiauth](https://github.com/sfelix-martins/passport-multiauth) package. To install it on another laravel project follow passport multiauth [readme](https://github.com/sfelix-martins/passport-multiauth/blob/4.0/README.md). Don’t forget to check the laravel version compatible with package version. Thanks!

**Comment by mdmusaib** [comment]
@sfelix-martins  My laravel version is 5.6.39, now I need to install passport multiauth can you share me the required documentation for help to install passport multiauth <=3.0 version

**Comment by sfelix-martins** [comment]
Follow the [Readme](https://github.com/sfelix-martins/passport-multiauth/blob/3.0/README.md) from branch 3.0.
