### ISSUE TITLE
security Issue,accessing all admin information even though am a user from user model

### ISSUE THREAD

**Issue by mdmusaib** [sfelix-martins/passport-multiauth-demo#6]

**Comment by mdmusaib** [comment]
@sfelix-martins  one issue even though I loggedIn as a user and got the tokens, now with that token I can't access admin routes right? but it can easily accessing admin routes with any protections , how is this be possible, I want to protect the admin routes how do I do that, pls help ASAP

**Comment by sfelix-martins** [comment]
Duplicated https://github.com/sfelix-martins/passport-multiauth/issues/63
