### ISSUE TITLE
Project uses older version of multi-auth

### ISSUE THREAD

**Issue by SachinBahukhandi** [sfelix-martins/passport-multiauth-demo#7]
Hi, Greetings and thank you for the working implementation of the **`multiauth`**. Its a cakewalk, however the repo uses an older version of **`multiauth`**. I tried to update the version to `4.0` and the example leads to this error:
**Argument 1 passed to Illuminate\Auth\Middleware\Authenticate::authenticate() must be of the type array, object given**
Kindly help. Thank you.

**Comment by sfelix-martins** [comment]
Hi, @SachinBahukhandi 
The version `4.0` required laravel `5.7`. You should upgrade the laravel version before.
Thanks!
